WHITESPACE = _{ " " | "\t" | "\n" | "\r" }

expression = { term ~ (WHITESPACE* ~ operator ~ WHITESPACE* ~ term)* }

term = _{ component | function_call | ident | string | integer }

component = { "<" ~ (!"/>" ~ ANY)* ~ "/>" }

function_call = { ident ~ WHITESPACE* ~ "(" ~ WHITESPACE* ~ argument_list? ~ WHITESPACE* ~ ")" }
argument_list = _{ term ~ (WHITESPACE* ~ "," ~ WHITESPACE* ~ term)* }

ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
operator = { "+" | "-" | "*" | "/" }

integer = @{ (ASCII_DIGIT | "_")+ }
string = @{ "\"" ~ (escape_sequence | !("\"" | "\\") ~ ANY)* ~ "\"" }

escape_sequence = { "\\" ~ ( "\"" | "\\" | "n" | "t" | "r" ) }
